### ISSUE TITLE
evaluate the ckpt cityscapes,the miou is too low';when to intialize it to train,it has the error

### ISSUE THREAD

**Issue by coldsheephot** [DeepSceneSeg/AdapNet-pp#10]
the num_classes=12, the checkpoint is the RGB model:
when I use the checkpoint to  evalute:
8.62191438941 total_data:  500

why it is so low? -->I think it is not the finally model

------------

when I train it ,use the intialize, the has the error:

ValueError: No variables to save

_Originally posted by @coldsheephot in https://github.com/DeepSceneSeg/AdapNet-pp/issues/9#issuecomment-492482156_

**Comment by coldsheephot** [comment]
the variable name of the cityscapes ckpt is:
'Global_Step ' ,'resnet_v2_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta '

but the import_variables is such like this:
Global_Step:0
resnet_v2_50/conv0/BatchNorm/gamma:0

so I can not do the training by the ckpt;and eval miou is too low

**Comment by githubfragments** [comment]
I also evaluted the num_classses=12 AdapNet model on rgb images of Cityscapes, the mIou is almost the same as the reported. There may be somewhere wrong with your procedures @coldsheephot. 

But when I evaluate the num_classes==19 model on rgb images of Cityscapes using the pretrained weights, the mIoU is 78.5%. There exists a large gap to the mIoU (81.24) that was reported in the paper. Is this normal?  @avalada 

I am trying to reproduce the accuracy, i.e. 81.24% on the val set and 81.34 on the test set. How should I do to get those accuraies?

**Comment by githubfragments** [comment]
Thanks for your nice work @avalada   Another issue, what's the full resolution of ScanNet refer to? The rgb images' resolution is 1296x968, and depth images' resolution is 640x480. What are the sizes you used to train AdapNet_pp and SSMA.

**Comment by avalada** [comment]
@coldsheephot Replace in line 70 and 71 var.name with var.name.replace(':0','') in train.py. That should do the trick. If you initialize the network with the initial checkpoint that we give then train.py should work without a problem. But while initializing with our pretrained model you'll have to modify as mentioned above. 

@githubfragments We don't provide the checkpoint for 81.34 as yet, its still work in progress. The 78.5 that you get is single scale evaluation. Inference techniques such as multiscale and flip should get it closer to 81.

**Comment by coldsheephot** [comment]
@githubfragments hello,can you provide the cityscape dataset?

I think my dataset is wrong.
because I just get the tfrecords,and eidt the helper.py (resize(384,768)) 
I think the dataset is something wrong

**Comment by coldsheephot** [comment]
when I use evaluate.py:
I just get the val.tfrecords by using the convert_to_tfrecords.py 
and then: the size=1024*2048
when I evaluate it, I modify the helper.py( resize the data and label)

the process is wrong? in which step ,should I resize the image ?

can  you provide the function or the datasets of cityscapes?
@avalada @githubfragments

**Comment by coldsheephot** [comment]
I  use the num_classes=20
and my dataset is the cityscapes fine images，it's label also has 20 num_classes
so it does not need the label class mapping

and then I just use the origin image and image label to get the tfrecords

when I evaluate it, I modify the helper.py( resize the data and label)

the process is wrong? in which step ,should I resize the image ?

**Comment by githubfragments** [comment]
The labels used for evaluation is not the same as the original labels of the Cityscapes. I would think you should remap the labels.

**Comment by avalada** [comment]
Sorry, we cannot share the cityscapes dataset or the tfrecords due to the licencing rules of Cityscapes

**Comment by coldsheephot** [comment]
In which step do you set the image_size to (384*768)
@githubfragments @avalada 


I use the preparation/createTrainIdLabelImgs.py to do id mapping ,and modify the TrainIDs of the labels,and get the labels
and then in the help.py ,I resize the images to 384*768
but the num_classes=20,the iou=66.3%

**Comment by coldsheephot** [comment]
Cityscapes (void + 11 classes):
0: Void
1: Sky
2: Building
3: Road
4: SideWalk
5: Fence
6: Vegetation
7: Pole
8: Car/Truck/Bus
9: Traffic Sign
10: Pedestrians
11: Rider/Bicycle/Motorcycle

and in num_classes=12, the 10: cityscapes has not the class pedestrains-->the person?

I use the preparation/createTrainIdLabelImgs.py to do id mapping ,and modify the TrainIDs of the labels,and get the labels
and then in the help.py ,I resize the images to 384*768
and finally get the moiu=80.55

**Comment by onizuka94** [comment]
> Cityscapes (void + 11 classes):
> 0: Void
> 1: Sky
> 2: Building
> 3: Road
> 4: SideWalk
> 5: Fence
> 6: Vegetation
> 7: Pole
> 8: Car/Truck/Bus
> 9: Traffic Sign
> 10: Pedestrians
> 11: Rider/Bicycle/Motorcycle
> 
> and in num_classes=12, the 10: cityscapes has not the class pedestrains-->the person?
> 
> I use the preparation/createTrainIdLabelImgs.py to do id mapping ,and modify the TrainIDs of the labels,and get the labels
> and then in the help.py ,I resize the images to 384*768
> and finally get the moiu=80.55

@coldsheephot

can you explain more what you did , I have the same issue with freiburg dataset , where and how do I do id mapping ? aren't the segmented ground truth images supposed to be our labels using the rgb color of each element in the image ?

**Comment by avalada** [comment]
pedestrians is equivalent to person class.
There is something wrong in the mapping. With the given miou that you get, I think most probably mapping of the void class is a miss somewhere.
Please ensure that all the classes other than the mentioned ones (sky, building, ...) have their trainid set to 0.
