### ISSUE TITLE
Inference file

### ISSUE THREAD

**Issue by Marwen-Bhj** [DeepSceneSeg/AdapNet-pp#13]
Hello , thanks for the interesting work , can you provide the inference.py file ?

**Comment by avalada** [comment]
You can use evaluate.py and just map the output predictions to color labels.

**Comment by ievbu** [comment]
Hello, I would like to ask you how can I try out your trained AdapNet++ network using images without creating tfrecord? I have tried loading the model and feeding single image (resized and reshaped), but results were not as expected.

**Comment by onizuka94** [comment]
> You can use evaluate.py and just map the output predictions to color labels.

can you specify more precisely how to do that within the code ?
