### ISSUE TITLE
Output Model File and Node names

### ISSUE THREAD

**Issue by ammar-mahmood** [DeepSceneSeg/AdapNet-pp#14]
Hi,

I have run the adaptnet-pp model on my own dataset with 2 classes. Can you guide me on how to convert the final checkpoint into a single ".pb" file which I can use for inference on other images?

Moreover, I will also need the names of the input and output nodes to be able to export the model checkpoint into a .pb file.

Looking forward to hearing back from you.

**Comment by avalada** [comment]
input op: Data/input
output op: Softmax

Note: while reading a frozen graph, (you'll find the code from TensorFlow git) graph.get_tensor_by_name('prefix/Softmax:0') expects the name in this format.
where prefix is the name of the prefix added during loading of the frozen graph.
         Softmax:0 names(output) of the operation
         Data/input:0 for input operation

frozen graph.py is directly taken from TensorFlow examples script to generate .pb checkpoints with small changes to suit our need.
to run:
python frozen_graph.py --model_dir address_to_model_folder (should contain checkpoint txt file) --output_node_names Softmax(in Adapnet-pp case) 
[frozen_graph.py.zip](https://github.com/DeepSceneSeg/AdapNet-pp/files/3477979/frozen_graph.py.zip)

**Comment by ammar-mahmood** [comment]
Thank you for the detailed response. I ran the following:
python frozen_graph.py --model_dir H:\AMR\AdapNet-pp\exp\training --output_node_names Softmax

 but I am getting the following error:

AssertionError: Softmax is not in graph

I tried viewing the graph in tensorbaord and also could not see a Softmax node. The closest one was 'resnet_v2_50/Softmax'. The code runs with this:

python frozen_graph.py --model_dir H:\AMR\AdapNet-pp\exp\training --output_node_names resnet_v2_50/Softmax

If I open the .meta file in a text editor, I am still able to find 'Softmax' defined in the file.

**Comment by avalada** [comment]
For our pre-trained checkpoints, Softmax should work out. 'resnet_v2_50/Softmax' seems right too (resnet_v2_50  as a prefix might be because of tf.variable_scope).
In the frozen_graph.py, you can uncomment line 54,55,56 to see the name of output_node.
