### ISSUE TITLE
Freiburg Forest ID mapping 

### ISSUE THREAD

**Issue by onizuka94** [DeepSceneSeg/AdapNet-pp#17]
I have a dataset containing both RGB and Segmented images as ground truth , the readme.txt included in the annotated dataset stated this :

GT_color :folder containing the groundtruth masks for semantic segmentation Annotations are given using a color representation, where each corresponds to a specific class. This is primairly provided for visualization. For training, create a corresponding ID image by assigning the colors to a specific class ID as given below.

Class		R	G	B	ID

Void		- 	- 	-	0

Road            170 	170 	170	1

Grass           0 	255 	0	2

Vegetation      102 	102 	51	3

Tree            0 	60 	0	3

Sky             0 	120 	255	4

Obstacle        0 	0 	0	5

I don't understand what's meant by "creating corresponding ID image" , aren't the segmented images labelled already by each area's color ? meaning that the rgb are the labels ?

**Comment by avalada** [comment]
The color gt ids (3 channel) are only for visualization. During training, you always use indexed ids (1 channel). For example:
Road (170 170 170) R G B corresponds in color gt. In train gt for each (y, x) where y belongs to (0, height) and x belongs to (0, width) is  RGB is (170 170 170)  you map it to 1.
similar for all the other classes.

In terms of the code, in python one way to do this is
let img be the color gt image(array)
and let img_sc be an array of zeros of same size as img but 1 channel.
img_sc[np.logical_and(np.logical_and(img[:,:,0]==170,img[:,:,1]==170),img[:,:,2]==170)] = 1
