### ISSUE TITLE
I used the provided pre-trained model for the freiburg forest dataset, but the mIoU is low

### ISSUE THREAD

**Issue by adhitir** [DeepSceneSeg/AdapNet-pp#18]
I ran the evaluate.py on the freiburg forest test data using the checkpoint provided in your readme for RGB data, but the mIoU is this:
mIoU:  3.464414239463952
mIoU:  4.031567725489401 total_data:  135

I'm clearly not doing something right.

**Comment by onizuka94** [comment]
refer to the issue number 17 , you probably didn't preprocess your data they way it should be , means you didn't map the inputs the way it's mentioned in the issue . I think they should really mention this in the instructions .

**Comment by adhitir** [comment]
Hi,

I should have updated it earlier. You are absolutely correct, I hadn't read the instructions in the Freiburg forest read-me and done the pre-processing steps mentioned there. 
After that, my mIoU came to about 77.8 percent, which is not the reported number, but still fairly close.

**Comment by avalada** [comment]
I guess this is solved.

Groundtruth mapping is already mentioned under the model section. Also added it under data section now.
