### ISSUE TITLE
Failed to find any matching files for init_checkpoint/Adapnet_pp_init.ckpt

### ISSUE THREAD

**Issue by kame-hameha** [DeepSceneSeg/AdapNet-pp#19]
Hello, I am trying to run the training script with the following config file "config/freiburg_forest_train.config":

`gpu_id: '0'
model: 'AdapNet_pp'
num_classes: 6
intialize: 'init_checkpoint/Adapnet_pp_init.ckpt'
checkpoint: ' '
train_data: 'dataset/tf_records'
batch_size: 8
skip_step: 5
height: 384
width: 768
max_iteration: 300
learning_rate: 0.000001
save_step: 100
power: 0.9
`

I am using a GeForce 1060 with 6GB and an Nvidia-docker with tensorFlow-1.14.0-gpu

Not sure what the problem is. I tried to find a solution but couldn't find anything. 

The checkpoint files are also in my folder `init_checkpoint`
-rw-rw-r-- 1 kame kame  90M Sep 13 09:22 AdapNet_pp_init.ckpt.data-00000-of-00001
-rw-rw-r-- 1 kame kame  12K Sep 13 09:22 AdapNet_pp_init.ckpt.index
-rw-rw-r-- 1 kame kame 5.7M Sep 13 09:22 AdapNet_pp_init.ckpt.meta
`

The full Traceback:
`Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main()
  File "train.py", line 126, in main
    train_func(config)
  File "train.py", line 64, in train_func
    reader = tf.train.NewCheckpointReader(config['intialize'])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 636, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 648, in __init__
    this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for init_checkpoint/Adapnet_pp_init.ckpt
`

**Comment by kame-hameha** [comment]
Just tried it on another Titan RTX with 24GB RAM...same problem. 

I guess the new_CheckpointReader which was introduced in tf version 1.14 has a problem which I do not comprehend ...

**Comment by deeplearning666** [comment]
Hello! Have you run the code in 'freiburg_forest_data' successfully? I have download the code but I can't find the code of 'config/freiburg_forest_train.config'. Can you help me?
I'm looking forward to seeing you soon!

**Comment by JunzWu** [comment]
Hi, I have the same error with you. Did you solve this problem? Could you please tell me how to solve it?
