### ISSUE TITLE
Comptute_iou

### ISSUE THREAD

**Issue by MarcSchotman** [DeepSceneSeg/AdapNet-pp#2]
Hi,

I am trying to use your `compute_iou()` function but I think my inputs to the `compute_output_matrix()` function are not what they should be... At the moment I am trying this:

```
num_classes= 3
output_matrix = compute_output_matrix(label_max =2,pred_max=2, output_matrix=model.softmax)
iou = comput_iou(output_matrix)
```

Assuming that the max label = max pred = num_classes -1? 
However I get a NoneType index..

Side note
------------
While scanning through your code I saw this:

```
 ### Upsample/Decoder
        with tf.variable_scope('conv41'):
            self.deconv_up1 = self.tconv2d(self.eAspp_out, 4, 256, 2)
            self.deconv_up1 = self.batch_norm(self.deconv_up1)

        self.up1 = self.conv_batchN_relu(tf.concat((self.deconv_up1, self.skip2), 3), 3, 1, 256, name='conv89') 
        self.up1 = self.conv_batchN_relu(self.up1, 3, 1, 256, name='conv96')
        with tf.variable_scope('conv16'):
            self.deconv_up2 = self.tconv2d(self.up1, 4, 256, 2)
            self.deconv_up2 = self.batch_norm(self.deconv_up2)
        self.up2 = self.conv_batchN_relu(tf.concat((self.deconv_up2, self.skip1), 3), 3, 1, 256, name='conv88') 
        self.up2 = self.conv_batchN_relu(self.up2, 3, 1, 256, name='conv95')
        self.up2 = self.conv_batchN_relu(self.up2, 1, 1, self.num_classes, name='conv78')
```
And from reading your paper it seems that skip1 and skip2 should be the other way around no?

**Comment by avalada** [comment]
1. compute_output_matrix(label_max,pred_max,output_matrix)
Here pred_max=np.argmax(model.softmax, 3) of the shape (B,H,W)
         label_max=np.argmax(one_hot_encoded_label, 3) of the shape (B, H, W)
         output_matrix is an array of zeros of the shape(num_classes, 3), the three columns being true positive, false positive and false negative which gets computed by the compute_output_matrix
We have added these as comments to the code.

2. The code itself is fine. Its just that the names for the skip connections are opposite of what is mentioned in the paper.

Note that label 0 is assumed as the void label.

**Comment by MarcSchotman** [comment]
Cheers, thanks for the explanation
