### ISSUE TITLE
Trained models for cityscapes-19+void class

### ISSUE THREAD

**Issue by Eddylib** [DeepSceneSeg/AdapNet-pp#4]
Hi, 
  Thanks for your great job, it inspired me deeply. The class of  standard evaulation of cityscape if of 19 classes. If its convenient to share corresponding trained models?

**Comment by avalada** [comment]
We have added a checkpoint for the 19-class model

**Comment by coldsheephot** [comment]
but I can not use the checkpoint becase it has the error:
OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key resnet_v2_50/beta1_power not found in checkpoint

**Comment by avalada** [comment]
Please see the other issue that you posted
