### ISSUE TITLE
Consistency between the implemented backbone and the initial weights

### ISSUE THREAD

**Issue by kazuto1011** [DeepSceneSeg/AdapNet-pp#5]
Thank you for sharing your great work.
Let me ask you a question about the provided initial weights `init_checkpoint/Adapnet_pp_init.ckpt.*`. According to the model definition in `models/AdapNet_pp.py`, this codebase implements ResNet v2 modified with the proposed multiscale residual units within block 3&4. However, I found the initial weights rather include parameters for ResNet v1. Is this appropriate to reproduce results or you have another file for the modified ResNet v2 trained on ImageNet?

**Comment by avalada** [comment]
That was just an error in the naming. The model is actually v2. We updated it.

**Comment by kazuto1011** [comment]
Thank you for the quick fix!
