### ISSUE TITLE
can you add the cityscape dataset process to the source code

### ISSUE THREAD

**Issue by coldsheephot** [DeepSceneSeg/AdapNet-pp#8]
Data
Augment the training data. In our work, we first resized the images in the dataset to 768x384 pixels and then apply a series of augmentations (random_flip, random_scale and random_crop).

Convert the training data (augmented), test data and validation data into the .tfrecords format. Create a .txt file for each set having entries in the following format:
________________________________________________________________
how to get the training data(augmented) ? just to process the picture and then save it ,and put the new image to the txt file?

**Comment by coldsheephot** [comment]
可否直接将数据处理全流程打通到代码里，包括数据增强？

can you add the data augmented souce code into the repo?

**Comment by avalada** [comment]
There are multiple ways to do this. You can do the augmentations online while training or preprocess them before training. The augmentation code is part of our internal tensorflow so we wont be able to release it.
